# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 05:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161228_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'\xe6\xad\xa3\xe6\x96\x87'),
        ),
    ]
